### ISSUE TITLE
Bug: Windows Server 无法启动 GUI

### ISSUE THREAD

**Issue by TRDSCSH** [koishijs/koishi-desktop#131]
## 问题描述
我在我的服务器上通过 Koishi 安装程序安装软件，然后启动，启动后不会自动弹出 GUI，http://127.0.0.1:5140/ 拒绝连接。
我尝试了多个版本，发现 1.0.2 1.0.1 0.11.3 这 3 个版本都无法成功启动，而 0.10.6 可以成功启动。

## 截图
<img width="296" alt="小图标菜单" src="https://github.com/koishijs/koishi-desktop/assets/125717891/1161ba53-2dbe-416b-bfd1-169d0eb7e59d">

## 信息
Windows 版本：Windows Server 2022 Datacenter
Koishi 桌面版本：1.0.2

**Comment by ilharp** [comment]
听起来是你的实例安装了某个插件，并且该插件不兼容 Node 20。

看下日志。 <https://k.ilharp.cc/555/2> 有获取日志的方法。

**Comment by TRDSCSH** [comment]
> 听起来是你的实例安装了某个插件，并且该插件不兼容 Node 20。
> 
> 看下日志。 https://k.ilharp.cc/555/2 有获取日志的方法。

好的，我把log打包上传。
[logs.zip](https://github.com/koishijs/koishi-desktop/files/14558586/logs.zip)

日志概览：
```
0000|3|2024-03-11 20:26:19 [D] launcher 触发操作：运行服务
0000|2|2024-03-11 20:26:19 [I] launcher 正在启动这些实例：
                        default
0000|3|2024-03-11 20:26:19 [D] launcher Writing daemon.lock...
0000|3|2024-03-11 20:26:19 [D] launcher Serving daemon...
1000|2|    at $x.resolve (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:205:84)
1000|2|Internal Error: @koishijs/boilerplate@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
1000|2|    at C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7182
1000|2|    at ne (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7162)
1000|2|    at Yy (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:140:5)
1000|2|    at Bd.resolve (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:141:1488)
1000|2|    at C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7788
0000|2|2024-03-11 20:26:20 [W] launcher Instance default exited with: exit status 1.
0000|3|2024-03-11 20:26:23 [D] launcher Client connected at 127.0.0.1:61928
0000|3|2024-03-11 20:26:23 [D] launcher Parsed request type: ping
0000|3|2024-03-11 20:26:23 [D] launcher Send pong back
0000|3|2024-03-11 20:26:23 [D] launcher Client connected at 127.0.0.1:61929
0000|3|2024-03-11 20:26:23 [D] launcher Parsed request type: ping
0000|3|2024-03-11 20:26:23 [D] launcher Send pong back
0000|3|2024-03-11 20:26:23 [D] launcher Client connected at 127.0.0.1:619
0000|3|2024-03-11 20:26:23 [D] launcher Parsed request type: cmd
0000|3|2024-03-11 20:26:23 [D] launcher Parsed command: ps
0000|3|2024-03-11 20:26:23 [D] launcher Acquired task 1
0001|3|2024-03-11 20:26:23 [D] launcher Trigger KoiCmd ps
0000|3|2024-03-11 20:26:23 [D] launcher Releasing task 1
0000|3|2024-03-11 20:26:27 [D] launcher 正在启动实例 default
0000|3|2024-03-11 20:26:27 [D] launcher Client connected at 127.0.0.1:619
0000|3|2024-03-11 20:26:27 [D] launcher Parsed request type: ping
0000|3|2024-03-11 20:26:27 [D] launcher Send pong back
0000|3|2024-03-11 20:26:27 [D] launcher Client connected at 127.0.0.1:619
0000|3|2024-03-11 20:26:27 [D] launcher Parsed request type: cmd
0000|3|2024-03-11 20:26:27 [D] launcher Parsed command: start
0000|3|2024-03-11 20:26:27 [D] launcher Acquired task 2
0002|3|2024-03-11 20:26:27 [D] launcher Trigger KoiCmd start
0002|2|2024-03-11 20:26:27 [I] launcher Starting instance default...
0000|3|2024-03-11 20:26:27 [D] launcher Releasing task 2
1000|2|    at $x.resolve (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:205:84)
1000|2|    at C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7182
1000|2|    at Bd.resolve (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:141:1488)
1000|2|    at ne (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7162)
1000|2|Internal Error: @koishijs/boilerplate@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
1000|2|    at Yy (C:\Program Files\Koishi\Desktop\bin\yarn.cjs:140:5)
1000|2|    at C:\Program Files\Koishi\Desktop\bin\yarn.cjs:210:7788
0000|2|2024-03-11 20:26:28 [W] launcher Instance default exited with: exit status 1.
0000|3|2024-03-11 20:26:29 [D] launcher 正在重建托盘
0000|3|2024-03-11 20:26:29 [D] launcher Client connected at 127.0.0.1:619
0000|3|2024-03-11 20:26:29 [D] launcher Parsed request type: ping
0000|3|2024-03-11 20:26:29 [D] launcher Send pong back
0000|3|2024-03-11 20:26:29 [D] launcher Client connected at 127.0.0.1:619
0000|3|2024-03-11 20:26:29 [D] launcher Parsed request type: cmd
0000|3|2024-03-11 20:26:29 [D] launcher Parsed command: ps
0000|3|2024-03-11 20:26:29 [D] launcher Acquired task 3
0003|3|2024-03-11 20:26:29 [D] launcher Trigger KoiCmd ps
0000|3|2024-03-11 20:26:29 [D] launcher Releasing task 3
```
@ilharp

**Comment by TRDSCSH** [comment]
> > Internal Error: @koishijs/boilerplate@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
> 
> 咦 哦 你可能是从一个非常旧的版本开始用的，然后一路升级上来的
> 
> 这类问题，看 https://k.ilharp.cc/6103 就可以了

感谢大佬指路，问题已通过使用命令 `koi yarn -n default set version berry && koi yarn -n default` 解决🎉

**Comment by kuektic** [comment]
我也出现了类似问题，但是按照以上过程仍然无法解决

**Comment by ilharp** [comment]
> 我也出现了类似问题，但是按照以上过程仍然无法解决

你确定你出现的是 **类似** 问题（0.10 可以启动，0.11 以上无法启动）吗？只有这类问题应当使用 <k.ilharp.cc/6103> 解决。如果是新安装的 Koishi Desktop 无法启动，直接使用 <k.ilharp.cc/984> 解决。

**Comment by kuektic** [comment]
> > 我也出现了类似问题，但是按照以上过程仍然无法解决
> 
> 你确定你出现的是 **类似** 问题（0.10 可以启动，0.11 以上无法启动）吗？只有这类问题应当使用 <https://k.ilharp.cc/6103> 解决。如果是新安装的 Koishi Desktop 无法启动，直接使用 <https://k.ilharp.cc/984> 解决。
> 

谢了，解决了
